/**
 * Official VEX country and event-region vocabularies, and the mapping between
 * them. Extracted from app/page.tsx: pure data with no React or DOM
 * dependency, and the one place the country -> region relationship is encoded.
 */

export const vexCountries = ['All','United States','China','Canada','Australia','Europe','Asia Pacific','United Kingdom','Ireland','New Zealand','Taiwan','Hong Kong','Mexico','Afghanistan','Algeria','American Samoa','Andorra','Austria','Azerbaijan','Bahrain','Bangladesh','Barbados','Belgium','Belize','Bermuda','Bhutan','Bolivia','Brazil','Brunei','Burkina Faso','Burundi','Cambodia','Cayman Islands','Chile','Colombia','Cook Islands','Czech Republic','Côte d’Ivoire','Dominican Republic','East Timor','Egypt','Estonia','Ethiopia','Finland','France','Gambia','Georgia','Germany','Ghana','Guam','Guatemala','Guyana','Haiti','India','Indonesia','Iraq','Japan','Jordan','Kazakhstan','Kenya','Kuwait','Kyrgyzstan','Laos','Lebanon','Lesotho','Liberia','Libya','Lithuania','Luxembourg','Macau','Malaysia','Mali','Mauritania','Mongolia','Morocco','Mozambique','Myanmar','Nepal','Netherlands','Nigeria','North Korea','Northern Mariana Islands','Oman','Pakistan','Palestine','Panama','Papua New Guinea','Paraguay','Peru','Philippines','Poland','Puerto Rico','Qatar','Romania','Russia','Saudi Arabia','Senegal','Sierra Leone','Singapore','Slovakia','Slovenia','South Africa','South Korea','Spain','Sri Lanka','Suriname','Switzerland','Tajikistan','Thailand','Tunisia','Turkmenistan','Türkiye','U.S. Virgin Islands','Uganda','United Arab Emirates','Uzbekistan','Vietnam','Zimbabwe'];

export const vexEventRegions = ['All','Afghanistan','Alabama','Alaska','Alberta/Saskatchewan','Algeria','American Samoa','Andorra','Arizona','Arkansas','Australia','Austria','Azerbaijan','Bahrain','Bangladesh','Barbados','Belgium','Belize','Bermuda','Bhutan','Bolivia','Brazil','British Columbia (BC)','Brunei','Burkina Faso','Burundi','California - Region 1','California - Region 2','California - Region 3','California - Region 4','Cambodia','Cayman Islands','Chile','Chinese Taipei','Colombia','Colorado','Connecticut','Cook Islands','Czech Republic','Côte d’Ivoire','Delaware','Delmarva','District of Columbia','Dominican Republic','East China','East Timor','Egypt','Estonia','Ethiopia','Finland','Florida - North/Central','Florida - South','France','Gambia','Georgia','Georgia- Country','Germany','Ghana','Guam','Guatemala','Guyana','Haiti','Hawaii','Hong Kong','Idaho','Illinois','India','Indiana','Indonesia','Iowa','Iraq','Ireland','Japan','Jordan','Kansas','Kazakhstan','Kentucky','Kenya','Kuwait','Kyrgyzstan','Laos','Lebanon','Lesotho','Liberia','Libya','Lithuania','Louisiana','Luxembourg','Macau','Maine','Malaysia','Mali','Manitoba','Maryland','Massachusetts','Mauritania','Mexico','Michigan','Middle China','Minnesota','Mississippi','Missouri','Mongolia','Montana','Morocco','Mozambique','Myanmar','Nebraska','Nepal','Netherlands','Nevada','New Brunswick/Nova Scotia/Prince Edward Island','New Hampshire/Vermont','New Jersey','New Mexico','New York-North','New York-South','New Zealand','Newfoundland and Labrador','Nigeria','North Carolina','North China','North Dakota','North Korea','Northern Mariana Islands','Nunavut','Ohio','Oklahoma','Oman','Ontario','Oregon','Pakistan','Palestine','Panama','Papua New Guinea','Paraguay','Pennsylvania - East','Pennsylvania - West','Peru','Philippines','Poland','Puerto Rico','Qatar','Quebec','Rhode Island','Romania','Russia','Saudi Arabia','Senegal','Sierra Leone','Singapore','Slovakia','Slovenia','South Africa','South Carolina','South China','South Dakota','South Korea','Southern New England','Spain','Sri Lanka','Suriname','Switzerland','Tajikistan','Tennessee','Texas - Region 1','Texas - Region 2','Texas - Region 3','Texas - Region 4','Texas - Region 5','Texas - Region 6','Thailand','Tunisia','Turkmenistan','Türkiye','U.S. Virgin Islands','Uganda','Unassigned','United Arab Emirates','United Kingdom','Utah','Uzbekistan','Vancouver Island (BC)','Vietnam','Virginia','Washington','West China','West Virginia','Wisconsin','Wyoming','Zimbabwe'];

export const usEventRegions = ['Alabama','Alaska','Arizona','Arkansas','California - Region 1','California - Region 2','California - Region 3','California - Region 4','Colorado','Connecticut','Delaware','Delmarva','District of Columbia','Florida - North/Central','Florida - South','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire/Vermont','New Jersey','New Mexico','New York-North','New York-South','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania - East','Pennsylvania - West','Rhode Island','South Carolina','South Dakota','Southern New England','Tennessee','Texas - Region 1','Texas - Region 2','Texas - Region 3','Texas - Region 4','Texas - Region 5','Texas - Region 6','Utah','Virginia','Washington','West Virginia','Wisconsin','Wyoming'];
export const canadaEventRegions = ['Alberta/Saskatchewan','British Columbia (BC)','Manitoba','New Brunswick/Nova Scotia/Prince Edward Island','Newfoundland and Labrador','Nunavut','Ontario','Quebec','Vancouver Island (BC)'];
export const chinaEventRegions = ['East China','Middle China','North China','South China','West China'];
export const europeEventRegions = ['Andorra','Austria','Belgium','Czech Republic','Estonia','Finland','France','Germany','Ireland','Lithuania','Luxembourg','Netherlands','Poland','Romania','Russia','Slovakia','Slovenia','Spain','Switzerland','Türkiye','United Kingdom'];
export const asiaPacificEventRegions = ['American Samoa','Australia','Cambodia','Cook Islands','East Timor','Guam','Hong Kong','Indonesia','Japan','Macau','Malaysia','Myanmar','New Zealand','Northern Mariana Islands','Papua New Guinea','Philippines','Singapore','South Korea','Thailand','Vietnam'];

export function eventRegionsForCountry(country) {
  if (country === 'All') return vexEventRegions;
  const groups = { 'United States': usEventRegions, Canada: canadaEventRegions, China: chinaEventRegions, Europe: europeEventRegions, 'Asia Pacific': asiaPacificEventRegions };
  const aliases = { Taiwan: 'Chinese Taipei', Georgia: 'Georgia- Country' };
  const matches = groups[country] ?? [aliases[country] ?? country].filter(region => vexEventRegions.includes(region));
  return ['All', ...matches];
}
